require 'kaminari/active_graph/version'
require 'active_support'
require 'active_graph'
require 'kaminari'
require 'kaminari/models/configuration_methods'
require 'kaminari/active_graph/criteria_methods'
require 'kaminari/active_graph/paginated'
require 'kaminari/active_graph/extension'
require 'kaminari/active_graph/hooks'
Kaminari::ActiveGraph::Hooks.init
